---
title: "Plotly and `flexdashboard`"
output:
  html_document: 
    toc: true
    toc_float: true
---

```{r, include = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(plotly)

library(p8105.datasets)

#styling stuff
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```



```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

### plotly scatterplot
```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  #what to have on hover label; /n adds a line break
  plot_ly(
    x = ~lat, 
    y = ~long, 
    type = "scatter", 
    mode = "markers",
    color = ~price, 
    text = ~text_label, #label that appears when hovering (need to add mutate function)
    alpha = 0.5)
```


### plotly boxplot
```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, 
          color = ~neighbourhood, 
          type = "box", 
          colors = "viridis")
```


### plotly barchart
```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, 
          y = ~n, 
          color = ~neighbourhood, 
          type = "bar", 
          colors = "viridis") # color coding
```



```{r}

```

